# Generated by Django 5.2.7 on 2025-10-24 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('Q1', 'Enero-Marzo'), ('Q2', 'Abril-Junio'), ('Q3', 'Julio-Septiembre'), ('Q4', 'Octubre-Diciembre')], max_length=2)),
                ('año', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('entregada', 'Entregada'), ('sin_entregar', 'Sin entregar')], max_length=20)),
                ('fase', models.CharField(choices=[('no_entregada', 'No entregada por el conductor'), ('en_firma', 'En firma del supervisor'), ('entregada', 'Entregada'), ('desvinculado', 'Desvinculado'), ('licencia', 'Licencia médica')], max_length=20)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conductor')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periodo')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supervisor')),
            ],
        ),
    ]
