# Generated by Django 5.2.7 on 2025-11-21 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_perfil_conductor_relacionado_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='base',
            field=models.CharField(choices=[('calle_larga', 'Spot Calle Larga'), ('lampa', 'Spot Lampa')], default='calle_larga', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conductor',
            name='perfil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.perfil'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='base',
            field=models.CharField(choices=[('calle_larga', 'Spot Calle Larga'), ('lampa', 'Spot Lampa')], default='calle_larga', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='base',
            field=models.CharField(choices=[('calle_larga', 'Spot Calle Larga'), ('lampa', 'Spot Lampa')], default='calle_larga', max_length=50),
            preserve_default=False,
        ),
    ]
