# Generated by Django 5.2.7 on 2025-11-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conductor_base_conductor_perfil_entrega_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='numero_registro',
            field=models.PositiveIntegerField(blank=True, editable=False, unique=True),
        ),
    ]
