# Generated by Django 5.2.7 on 2025-11-21 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='conductor_relacionado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_relacionado', to='core.conductor'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='supervisor_relacionado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supervisor'),
        ),
    ]
